name = "BaseFITS"
uuid = "b056ee54-6bb4-44e7-9abb-abfb59909e18"
authors = ["Éric Thiébaut <eric.thiebaut@univ-lyon1.fr> and contributors"]
version = "0.3.7"

[deps]
Compat = "34da2185-b29b-5c13-b0c7-acf172513d20"
Dates = "ade2ca70-3891-5945-98fb-dc099432e06a"
Requires = "ae029012-a4dd-5104-9daa-d747884805df"
TypeUtils = "c3b1956e-8857-4d84-9b79-890df85b1e67"

[compat]
Requires = "1"
Compat = "2, 3, 4"
TypeUtils = "≥ 0.2"
julia = "1.0"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
